"""Fixed imports

Revision ID: 3f70e0d0d582
Revises: 
Create Date: 2025-03-02 15:40:10.654510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f70e0d0d582'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('direct_messages', 'reciever_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_info', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_info', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('group_info', 'invite_code',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('group_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_members', 'member_role',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('group_messages', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_auth', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('user_auth', 'password',
               existing_type=sa.CHAR(length=73),
               type_=sa.String(length=73),
               existing_nullable=False)
    op.alter_column('user_auth', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_auth', 'friend_code',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=4),
               nullable=False,
               existing_server_default=sa.text('gen_random_bytes(4)'))
    op.create_index(op.f('ix_user_auth_user_id'), 'user_auth', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'user_auth', ['friend_code'])
    op.alter_column('user_messages', 'sent_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_messages', 'reply_to',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user_messages', 'read_reciepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_messages', 'read_reciepts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_messages', 'reply_to',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('user_messages', 'sent_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'user_auth', type_='unique')
    op.drop_index(op.f('ix_user_auth_user_id'), table_name='user_auth')
    op.alter_column('user_auth', 'friend_code',
               existing_type=sa.String(length=4),
               type_=postgresql.BYTEA(),
               nullable=True,
               existing_server_default=sa.text('gen_random_bytes(4)'))
    op.alter_column('user_auth', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_auth', 'password',
               existing_type=sa.String(length=73),
               type_=sa.CHAR(length=73),
               existing_nullable=False)
    op.drop_column('user_auth', 'is_deleted')
    op.alter_column('group_messages', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_members', 'member_role',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('group_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_info', 'invite_code',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('group_info', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('group_info', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('direct_messages', 'reciever_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
