"""feat: added chat id's to group and direct chats

Revision ID: be52fb25557a
Revises: 04541b72c69e
Create Date: 2025-03-14 16:44:21.056639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be52fb25557a'
down_revision: Union[str, None] = '04541b72c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('chat_id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('group_messages', sa.Column('chat_id', sa.BigInteger(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_messages', 'chat_id')
    op.drop_column('direct_messages', 'chat_id')
    # ### end Alembic commands ###
