"""fix: fixed primary indices for group and direct messages

Revision ID: f20562ce65bb
Revises: be52fb25557a
Create Date: 2025-03-14 17:07:25.776242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20562ce65bb'
down_revision: Union[str, None] = 'be52fb25557a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
